### GET with API master should be successful
GET {{BaseUrl}}/WeatherForeCast
Accept: application/json
Content-Type: application/json
ApiKey: {{ApiMasterKey}}

> {%
client.test("Calling weather controller with ApiKey", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}


### GET without key should cause 401
GET {{BaseUrl}}/WeatherForeCast
Accept: application/json
Content-Type: application/json

> {%
client.test("Call Weather controller without ApiKey --> 401", function() {
  client.assert(response.status === 401, "Response status is not 401");
});
%}


### GET with new API key should be successful
GET {{BaseUrl}}/WeatherForeCast
Accept: application/json
Content-Type: application/json
ApiKey: {{new_api_key}}

> {%
client.test("Calling weather controller with ApiKey", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}


### GET with unknown key should cause 401
GET {{BaseUrl}}/WeatherForeCast
Accept: application/json
Content-Type: application/json
ApiKey: {{unauthorized_api_key}}

> {%
client.test("Calling weather controller with ApiKey", function() {
  client.assert(response.status === 401, "Response status is not 401");
});
%}


### 
GET {{BaseUrl}}/WeatherForeCast
Accept: application/json
Content-Type: application/json
ApiKey: {{new_api_key}}

> {%
client.test("Calling weather controller with ApiKey", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}
###
